### ISSUE TITLE
qr-code: improve UX to suggest scan

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#71]

**Comment by vdias38** [comment]
Hide qrcode if min-width = 576px

```css
@media (min-width: 576px) {
  /* Hide all elements with the .hide-sm-up class when the minimum width is 576px (sm breakpoint) */
  .hide-sm-up {
    display: none;
  }

  /* Show all elements with the .show-sm-up class when the minimum width is 576px (sm breakpoint) */
  .show-sm-up {
    display: block;
  }
}
```
