### ISSUE TITLE
update layout of comments-list for better rendering on desktop

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#90]
![LinkedIn](https://user-images.githubusercontent.com/9011612/73093091-bd1d6d80-3ed5-11ea-848e-0c9715ffd776.png)

**Comment by vdias38** [comment]
https://ionicframework.com/blog/tips-tricks-for-ionic-on-desktop/

- [ ] Using the fixed grid on pages
  - [Width of the grid for different screen sizes when fixed is enabled](https://github.com/ionic-team/ionic/blob/master/core/src/components/grid/grid.vars.scss)
- [ ] Horizontally center the header & footer toolbars
```scss
  $ion-grid-width-lg: 960px;
  $ion-grid-width-xl: 1140px;

  @media (min-width: $ion-grid-width-lg) {
    ion-toolbar {
      margin: 0;
      padding-right: calc((100% - #{$ion-grid-width-lg}) / 2);
      padding-left: calc((100% - #{$ion-grid-width-lg}) / 2);
    }
  }
  @media (min-width: $ion-grid-width-xl) {
    ion-toolbar {
      margin: 0;
      padding-right: calc((100% - #{$ion-grid-width-xl}) / 2);
      padding-left: calc((100% - #{$ion-grid-width-xl}) / 2);
    }
  }
```
OBS: [can't use css var in media queries](https://ionicframework.com/docs/theming/advanced#variables-in-media-queries), it's why we use sass vars
- [ ] Showing tabs at the top
  - didn't achieve it, tabs overlap toolbar when set slot to top
- [ ] Set tabs icons on the left on desktop
  - `<ion-tab-button tab="profiles" layout="icon-start">`
